# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{k_means}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["reddavis"]
  s.date = %q{2009-08-15}
  s.description = %q{Attempting to create a fast memory efficient KMeans}
  s.email = %q{reddavis@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "benchmark/benchmark.rb",
     "k_means.gemspec",
     "lib/basic_cache_store.rb",
     "lib/ext/enumerable.rb",
     "lib/k_means.rb",
     "profiling/profile.rb",
     "test/ext/test_enumerable.rb",
     "test/helper.rb",
     "test/test_k_means.rb"
  ]
  s.homepage = %q{http://github.com/reddavis/k_means}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{K Means algorithm}
  s.test_files = [
    "test/ext/test_enumerable.rb",
     "test/helper.rb",
     "test/test_k_means.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
